using UnityEngine;
using System.Collections.Generic;
using System;

public enum FighterAnimation { WALK_FORWARD, WALK_BACKWARD, IDLE, BLOCK, DEATH, FLINCH_UP, FLINCH_DOWN,
	REGULAR_ATTACK, REGULAR_FORWARD_ATTACK, REGULAR_BACK_ATTACK, REGULAR_UP_ATTACK, REGULAR_DOWN_ATTACK, 
	UNIQUE_ATTACK, UNIQUE_FORWARD_ATTACK, UNIQUE_BACK_ATTACK, UNIQUE_UP_ATTACK, UNIQUE_DOWN_ATTACK, 
	SPECIAL_ATTACK, SPECIAL_FORWARD_ATTACK, SPECIAL_BACK_ATTACK, SPECIAL_UP_ATTACK, SPECIAL_DOWN_ATTACK, 
};

//public enum MoveCommand { FORWARD, FORWARD_DOWN, FORWARD_UP, BACK, BACK_DOWN, BACK_UP, UP, DOWN, NONE };
/*
public enum ActionCommand {  NONE, BLOCK,
	REGULAR, REGULAR_FORWARD, REGULAR_BACK, REGULAR_UP, REGULAR_DOWN,
	UNIQUE, UNIQUE_FORWARD, UNIQUE_BACK, UNIQUE_UP, UNIQUE_DOWN, 
	SPECIAL, SPECIAL_FORWARD, SPECIAL_BACK, SPECIAL_UP, SPECIAL_DOWN
};
*/
public enum Location { HIGH, LOW, NONE };

public enum MovementProperties { RAPID_FIRE, AIR_OK, AIR_ONLY, JUMP_CANCEL, D_JUMP_CANCEL, DASH_CANCEL, AIR_DASH_CANCEL, NONE };

public enum HitProperties { LOW, HIGH, UNBLOCKABLE, DMG_ON_BLOCK, THROW, AIR_THROW };

